### ISSUE TITLE
usability and purpose unclear to casual observer or new user

### ISSUE THREAD

**Issue by davidbuzz** [nasa/icarous#17]
Github needs embedded video demo, or at least screen shot of what it might look like in-use,  also perhaps flowchart/s of how it works would be good too.

**Comment by SweeWarman** [comment]
@davidbuzz Thank you for your feedback. We are currently working on a more detailed user guide with illustrations of use cases. Should be available within the next couple of weeks.

**Comment by SweeWarman** [comment]
This is still a work in progress, but here it is: https://nasa.github.io/icarous/
