### ISSUE TITLE
make error cannot find -lwrap

### ISSUE THREAD

**Issue by aogrcs** [nasa/icarous#42]
Hi, when I make cpu1-install, there is an error:
/usr/bin/ld: cannot find -lwrap
So I miss some thing? Thanks!
Sincerely

**Comment by SweeWarman** [comment]
Please see https://github.com/nasa/icarous/blob/master/Modules/README.md

**Comment by aogrcs** [comment]
I  have libwrap, but can not find it!
![screenshot from 2018-07-05 17-31-20](https://user-images.githubusercontent.com/5660925/42315304-b3650dfa-8079-11e8-96a2-523b36dc3b1e.png)

**Comment by SweeWarman** [comment]
cFS creates 32 bit binaries and you may not have the 32 bit version of the libwrap library installed. Since the libwap you have is located under x86_64/ and your compiler is not locating libwrap, I am guessing that your libwrap is a 64 bit library. Please follow the instructions under: https://github.com/nasa/icarous/blob/master/Modules/README.md to install the 32 bit version of the library.

**Comment by aogrcs** [comment]
Hi, I did it, thanks a lot

**Comment by UGoyal09** [comment]
Hello Aogrcs,

I am also trying to install the incarous in my system, but it is giving the errors which are:

Linking CXX shared library ../../../../../Modules/Plexil/lib/libPlexilValue.so
/usr/bin/ld: cannot find -lwrap
collect2: error: ld returned 1 exit status
Modules/Plexil/src/value/CMakeFiles/PlexilValue.dir/build.make:250: recipe for target '../Modules/Plexil/lib/libPlexilValue.so' failed
make[6]: *** [../Modules/Plexil/lib/libPlexilValue.so] Error 1
CMakeFiles/Makefile2:795: recipe for target 'Modules/Plexil/src/value/CMakeFiles/PlexilValue.dir/all' failed
make[5]: *** [Modules/Plexil/src/value/CMakeFiles/PlexilValue.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make[4]: *** [all] Error 2
CMakeFiles/cpu1-install.dir/build.make:57: recipe for target 'CMakeFiles/cpu1-install' failed
make[3]: *** [CMakeFiles/cpu1-install] Error 2
CMakeFiles/Makefile2:293: recipe for target 'CMakeFiles/cpu1-install.dir/all' failed
make[2]: *** [CMakeFiles/cpu1-install.dir/all] Error 2
CMakeFiles/Makefile2:300: recipe for target 'CMakeFiles/cpu1-install.dir/rule' failed
make[1]: *** [CMakeFiles/cpu1-install.dir/rule] Error 2
Makefile:264: recipe for target 'cpu1-install' failed
make: *** [cpu1-install] Error 2

I have installed the i386 architecture, also add it and also installed all the dependencies and libraries which are given on the link https://wiki.ubuntu.com/MultiarchCross

So can you please help me, that how you have managed to solve this issue.
