### ISSUE TITLE
question about interacting with ICAROUS

### ISSUE THREAD

**Issue by aogrcs** [nasa/icarous#50]
Hi,
I use ubuntu 16.04 64 and python 2.7 for ICAROUS, I have some question about this:
1 In the file SetupMavProxy.sh, there is a line " echo "Path to mavproxy modules: $MAVPROXY_PATH/MAVProxy/MAVProxy/modules/" ", Is this /MAVProxy redundant?
2 I do not find setup.py in the fold $MAVPROXY_PATH/MAVProxy, my MAVProxy version is 1.6.4
Thanks

**Comment by aogrcs** [comment]
Is this operation right? Thank!
![default](https://user-images.githubusercontent.com/5660925/45349711-99a99980-b5e4-11e8-8a1e-dd6c0035595b.JPG)

**Comment by SweeWarman** [comment]
The /MAVProxy path is not redundant. If you look into the MAVProxy repository, you will notice that there is another MAVProxy folder within which all the source code is located.

The last time I checked, the setup.py folder is still available. See here: https://github.com/ArduPilot/MAVProxy

It seems like you have installed all the modules. You also need to launch the Icarous application and also the SITL simulator. Please consult the README for instructions.

**Comment by aogrcs** [comment]
Hi,
Could I use the MAVProxy installed by pip? First I used this, so I did not find the setup.py. Thanks

**Comment by aogrcs** [comment]
HI,
The ICAROUS application means to start it by sudo ./core-cpu1, the SITL simulator means start the ArduCopter SITL? Thanks

**Comment by SweeWarman** [comment]
You might be able to use the one installed by pip. In that case, you may have to locate where MAVProxy is installed and then copy the custom modules into the module directory. I haven't done this before so I'm not sure if this method works.

Yes. run core-cpu1 and the ardupilot sitl.

**Comment by aogrcs** [comment]
Thanks, I will test this tomorrow, thanks for your patience!

**Comment by aogrcs** [comment]
Hi
I can run core-cpu1 and ardupilot sitl, please see attachment. But I have a simple question about how the core-cpu1 interface with ardupilot sitl or what's the effect of the core-cpu1? Thanks
![default](https://user-images.githubusercontent.com/5660925/45398305-336d5700-b676-11e8-9a30-108b1d12d1a3.JPG)

**Comment by aogrcs** [comment]
Hi
I want to start the example and do as following the readme file, first wo load, then geofence load and at last long MISSION_START, but I do not see the quadrotor takeoff. Did I do some thing incorrect or miss some thing? Thanks
![default](https://user-images.githubusercontent.com/5660925/45401547-ab8e4980-b683-11e8-8705-ebbfbe62d8f6.JPG)

**Comment by SweeWarman** [comment]
* core-cpu1 is launches the cFS middleware and all the icarous apps and services that are configured to run in this middle ware. 

* When you build with cmake, did you use the -DSITL=ON option as instructed in the README? You need to use this flag if you want to run icarous with the SITL.

* If you've compiled with the above flag, when you launch SITL and if core-cpu1 is running, you should see a state message on the core-cpu1 terminal saying "connection to autopilot established".

* You would also see status messages on the core-cpu1 terminal when you send commands from the MAVProxy ground station. If you don't see them, then your applications are not talking to each other.

**Comment by aogrcs** [comment]
Hi,
1 I run in the error directory /build-sitl/cpu1
2 I use -DSITL=ON
Now I run in /cFS/bin/cpu1, there is another error: 
1970-012-14:03:20.25313 ES Startup: Loading file: /cf/ardupilot.so, APP: ARDUPILOT
1970-012-14:03:20.25360 ES Startup: Could not load cFE application file:/cf/ardupilot.so. EC = 0xFFFFFFFF. Thanks

**Comment by aogrcs** [comment]
Hi,
All logs are:

talos@talos-virtual-machine:~/icarous/cFS/bin/cpu1$ sudo ./core-cpu1
[sudo] password for talos: 
CFE_PSP: Default Reset Type = PO
CFE_PSP: Default Reset SubType = 1
CFE_PSP: Default CPU ID = 1
CFE_PSP: Default Spacecraft ID = 42
CFE_PSP: Default CPU Name: cpu1
CFE_PSP: Starting the cFE with a POWER ON reset.
CFE_PSP: Clearing out CFE CDS Shared memory segment.
CFE_PSP: Clearing out CFE Reset Shared memory segment.
CFE_PSP: Clearing out CFE User Reserved Shared memory segment.
2018-256-02:41:29.23346 POWER ON RESET due to Power Cycle (Power Cycle).
2018-256-02:41:29.23349 ES Startup: CFE_ES_Main in EARLY_INIT state
CFE_PSP: CFE_PSP_AttachExceptions Called
2018-256-02:41:29.23354 ES Startup: CFE_ES_Main entering CORE_STARTUP state
2018-256-02:41:29.23355 ES Startup: Starting Object Creation calls.
2018-256-02:41:29.23355 ES Startup: Calling CFE_ES_CDSEarlyInit
2018-256-02:41:29.23367 ES Startup: Calling CFE_EVS_EarlyInit
2018-256-02:41:29.23370 Event Log cleared following power-on reset
2018-256-02:41:29.23371 ES Startup: Calling CFE_SB_EarlyInit
2018-256-02:41:29.23392 ES Startup: Calling CFE_TIME_EarlyInit
1970-012-14:03:20.00000 ES Startup: Calling CFE_TBL_EarlyInit
1970-012-14:03:20.00022 ES Startup: Calling CFE_FS_EarlyInit
1970-012-14:03:20.00034 ES Startup: Core App: CFE_EVS created. App ID: 0
EVS Port1 42/1/CFE_EVS 14: No subscribers for MsgId 0x808,sender CFE_EVS
EVS Port1 42/1/CFE_EVS 1: cFE EVS Initialized. cFE Version 6.5.0.0
1970-012-14:03:20.05133 ES Startup: Core App: CFE_SB created. App ID: 1
1970-012-14:03:20.05137 SB:Registered 4 events for filtering
EVS Port1 42/1/CFE_SB 14: No subscribers for MsgId 0x808,sender CFE_SB
EVS Port1 42/1/CFE_SB 1: cFE SB Initialized
1970-012-14:03:20.10228 ES Startup: Core App: CFE_ES created. App ID: 2
EVS Port1 42/1/CFE_SB 14: No subscribers for MsgId 0x808,sender CFE_ES
EVS Port1 42/1/CFE_ES 1: cFE ES Initialized
EVS Port1 42/1/CFE_SB 14: No subscribers for MsgId 0x808,sender CFE_ES
EVS Port1 42/1/CFE_ES 2: Versions:cFE 6.5.0.0, OSAL 4.2.1.0, PSP 1.3.0.0, chksm 30560
EVS Port1 42/1/CFE_SB 14: No subscribers for MsgId 0x808,sender CFE_ES
EVS Port1 42/1/CFE_ES 91: Mission 4b263a9.Icarous, 4b263a9, 75beb86
EVS Port1 42/1/CFE_ES 92: Build 201809131034 talos@talos-virtual-machine
1970-012-14:03:20.15333 ES Startup: Core App: CFE_TIME created. App ID: 3
EVS Port1 42/1/CFE_TIME 1: cFE TIME Initialized
1970-012-14:03:20.20353 ES Startup: Core App: CFE_TBL created. App ID: 4
EVS Port1 42/1/CFE_TBL 1: cFE TBL Initialized.  cFE Version 6.5.0.0
1970-012-14:03:20.25404 ES Startup: Finished ES CreateObject table entries.
1970-012-14:03:20.25407 ES Startup: CFE_ES_Main entering CORE_READY state
1970-012-14:03:20.25413 ES Startup: Opened ES App Startup file: /cf/cfe_es_startup.scr
1970-012-14:03:20.25427 ES Startup: Loading file: /cf/sch.so, APP: SCH
1970-012-14:03:20.25453 ES Startup: SCH loaded and created
1970-012-14:03:20.25469 ES Startup: Loading file: /cf/ardupilot.so, APP: ARDUPILOT
1970-012-14:03:20.25535 ES Startup: Could not load cFE application file:/cf/ardupilot.so. EC = 0xFFFFFFFF
1970-012-14:03:20.25543 ES Startup: Loading file: /cf/plexil.so, APP: PLEXIL
1970-012-14:03:20.26431 ES Startup: PLEXIL loaded and created
1970-012-14:03:20.26439 ES Startup: Loading file: /cf/geofence.so, APP: GEOFENCE
1970-012-14:03:20.26469 ES Startup: GEOFENCE loaded and created
1970-012-14:03:20.26476 ES Startup: Loading file: /cf/traffic.so, APP: TRAFFIC
1970-012-14:03:20.26503 ES Startup: TRAFFIC loaded and created
1970-012-14:03:20.26511 ES Startup: Loading file: /cf/trajectory.so, APP: TRAJECTORY
1970-012-14:03:20.26570 ES Startup: TRAJECTORY loaded and created
1970-012-14:03:20.26578 ES Startup: Loading file: /cf/tracking.so, APP: TRACKING
1970-012-14:03:20.26590 ES Startup: TRACKING loaded and created
1970-012-14:03:20.26596 ES Startup: Loading file: /cf/logger.so, APP: LOG
1970-012-14:03:20.26608 ES Startup: LOG loaded and created
EVS Port1 42/1/SCH 1: SCH Initialized. Version 2.2.1.0
EVS Port1 42/1/TRACKING 0: Tracking App Initialized. Version 1.0
EVS Port1 42/1/TRAJECTORY 0: TRAJECTORY App Initialized. Version 1.0
EVS Port1 42/1/TRAFFIC 0: TRAFFIC App Initialized. Version 1.0
EVS Port1 42/1/GEOFENCE 0: Geofence App Initialized. Version 1.0
EVS Port1 42/1/PLEXIL 1: Plexil Initialized. Version 4.0
EVS Port1 42/1/LOG 0: Logging application initialized in logging mode. Version 1.0
1970-012-14:03:20.31696 ES Startup: CFE_ES_Main entering OPERATIONAL state
EVS Port1 42/1/CFE_TIME 21: Stop FLYWHEEL

CFE_PSP: Control-C Captured - Exiting cFE
CFE_PSP: Critical Data Store Shared memory segment removed
Reset Area Shared memory segment removed
User Reserved Area Shared memory segment removed
CFE_PSP: NOTE: After quitting the cFE with a Control-C signal, it MUST be started next time
     with a Poweron Reset ( --reset PO ).

**Comment by SweeWarman** [comment]
This seems to be a bug in the ardupilot cmake list. I will fix this in the repository. In the mean time, you can edit the CMakeLists.txt located in cFS/apps/ardupilot as follows:

replace the following line (line 21):
`
target_link_libraries(ardupilot Utils)
`
with:
`
link_directories(${MODULES_LIB})
`
`
target_link_libraries(ardupilot Utils)
`
`
set_target_properties(ardupilot PROPERTIES INSTALL_RPATH "${MODULES_LIB}")
`

**Comment by aogrcs** [comment]
Hi,
It does work! Thanks for your patience!
Sincerely

**Comment by aogrcs** [comment]
Hi,
In this user guide, there are two videos about ICAROUS, are they respond to case 1 and case 2? Thanks

**Comment by SweeWarman** [comment]
no!

**Comment by aogrcs** [comment]
Hi,
Thanks for your replay! I think it is a challenge to do this SITL!
Sincerely
