### ISSUE TITLE
How to fix -lwrap error? /usr/bin/x86_64-linux-gnu-ld: cannot find -lwrap

### ISSUE THREAD

**Issue by FabianSchuessler** [nasa/icarous#52]
Hello,
I am trying to compile Icarous and run into some errors. Would be nice if someone could help me out. I read the readme about compilation errors (https://github.com/nasa/icarous/blob/master/Modules/README.mdr). Following the error logs:

> root@username-VirtualBox:/home/username/icarous/icarous/build# make cpu1-installCMake Warning (dev) at cFS/cFE/cfe/cmake/version.cmake:52 (file):
>   Policy CMP0053 is not set: Simplify variable reference and escape sequence
>   evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   For input:
> 
>     '#define MISSION_CONFIG      \"@MISSIONCONFIG@\"\n'
> 
>   the old evaluation rules produce:
> 
>     '#define MISSION_CONFIG      "Icarous"
>     '
> 
>   but the new evaluation rules produce:
> 
>     '#define MISSION_CONFIG      "@MISSIONCONFIG@"
>     '
> 
>   Using the old result for compatibility since the policy is not set.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at cFS/cFE/cfe/cmake/version.cmake:52 (file):
>   Policy CMP0053 is not set: Simplify variable reference and escape sequence
>   evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   For input:
> 
>     '#define MISSION_NAME        \"@MISSION_NAME@\"\n'
> 
>   the old evaluation rules produce:
> 
>     '#define MISSION_NAME        "Icarous2"
>     '
> 
>   but the new evaluation rules produce:
> 
>     '#define MISSION_NAME        "@MISSION_NAME@"
>     '
> 
>   Using the old result for compatibility since the policy is not set.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> [  0%] Built target version
> [100%] Built target elf2cfetbl
> [100%] Built target mission-genfiles
> [ 32%] Built target ACCoRD
> [ 33%] Built target Utils
> [ 33%] Built target GeofenceMonitor
> [ 34%] Built target GeofenceTest
> [ 34%] Built target GeofenceTestC
> [ 43%] Built target ipc
> [ 43%] Built target pugixml
> [ 43%] Linking CXX shared library ../../../../../Modules/Plexil/lib/libPlexilValue.so
> /usr/bin/x86_64-linux-gnu-ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libwrap.so when searching for -lwrap
> /usr/bin/x86_64-linux-gnu-ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libwrap.a when searching for -lwrap
> /usr/bin/x86_64-linux-gnu-ld: cannot find -lwrap
> collect2: error: ld returned 1 exit status
> Modules/Plexil/src/value/CMakeFiles/PlexilValue.dir/build.make:250: recipe for target '../Modules/Plexil/lib/libPlexilValue.so' failed
> make[6]: *** [../Modules/Plexil/lib/libPlexilValue.so] Error 1
> CMakeFiles/Makefile2:753: recipe for target 'Modules/Plexil/src/value/CMakeFiles/PlexilValue.dir/all' failed
> make[5]: *** [Modules/Plexil/src/value/CMakeFiles/PlexilValue.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make[4]: *** [all] Error 2
> CMakeFiles/cpu1-install.dir/build.make:57: recipe for target 'CMakeFiles/cpu1-install' failed
> make[3]: *** [CMakeFiles/cpu1-install] Error 2
> CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/cpu1-install.dir/all' failed
> make[2]: *** [CMakeFiles/cpu1-install.dir/all] Error 2
> CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/cpu1-install.dir/rule' failed
> make[1]: *** [CMakeFiles/cpu1-install.dir/rule] Error 2
> Makefile:175: recipe for target 'cpu1-install' failed
> make: *** [cpu1-install] Error 2

Somehow libwrap is installed, but both tcpd version seem not to like each other.

> root@username-VirtualBox:/home/username/icarous/icarous/build# sudo apt-get install tcpd tcpd:i386
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> tcpd:i386 is already the newest version (7.6.q-27).
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  tcpd : Conflicts: tcpd:i386
>  tcpd:i386 : Conflicts: tcpd
> E: Unable to correct problems, you have held broken packages.

g++-multilib + gcc-multilib are installed

No idea how to install nlopt on Ubuntu and whether it is necessary.

**Comment by FabianSchuessler** [comment]
Thank you for your reply, I still have some issues after linking.

ln -sf /lib/i386-linux-gnu/libwrap.so.0 /usr/lib/x86_64-linux-gnu/libwrap.so

> root@username-VirtualBox:/home/username/icarous/icarous/build# make cpu1-installCMake Warning (dev) at cFS/cFE/cfe/cmake/version.cmake:52 (file):
>   Policy CMP0053 is not set: Simplify variable reference and escape sequence
>   evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   For input:
> 
>     '#define MISSION_CONFIG      \"@MISSIONCONFIG@\"\n'
> 
>   the old evaluation rules produce:
> 
>     '#define MISSION_CONFIG      "Icarous"
>     '
> 
>   but the new evaluation rules produce:
> 
>     '#define MISSION_CONFIG      "@MISSIONCONFIG@"
>     '
> 
>   Using the old result for compatibility since the policy is not set.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at cFS/cFE/cfe/cmake/version.cmake:52 (file):
>   Policy CMP0053 is not set: Simplify variable reference and escape sequence
>   evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   For input:
> 
>     '#define MISSION_NAME        \"@MISSION_NAME@\"\n'
> 
>   the old evaluation rules produce:
> 
>     '#define MISSION_NAME        "Icarous2"
>     '
> 
>   but the new evaluation rules produce:
> 
>     '#define MISSION_NAME        "@MISSION_NAME@"
>     '
> 
>   Using the old result for compatibility since the policy is not set.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> [  0%] Built target version
> [100%] Built target elf2cfetbl
> [100%] Built target mission-genfiles
> [ 32%] Built target ACCoRD
> [ 33%] Built target Utils
> [ 33%] Built target GeofenceMonitor
> [ 34%] Built target GeofenceTest
> [ 34%] Built target GeofenceTestC
> [ 43%] Built target ipc
> [ 43%] Built target pugixml
> [ 44%] Built target PlexilValue
> [ 44%] Building CXX object Modules/Plexil/src/utils/CMakeFiles/PlexilUtils.dir/JNIHelper.cc.o
> In file included from /home/username/icarous/icarous/Modules/Plexil/src/utils/JNIHelper.cc:28:0:
> /home/username/icarous/icarous/Modules/Plexil/src/utils/JNIHelper.hh:30:10: fatal error: jni.h: No such file or directory
>  #include <jni.h>
>           ^~~~~~~
> compilation terminated.
> Modules/Plexil/src/utils/CMakeFiles/PlexilUtils.dir/build.make:158: recipe for target 'Modules/Plexil/src/utils/CMakeFiles/PlexilUtils.dir/JNIHelper.cc.o' failed
> make[6]: *** [Modules/Plexil/src/utils/CMakeFiles/PlexilUtils.dir/JNIHelper.cc.o] Error 1
> CMakeFiles/Makefile2:808: recipe for target 'Modules/Plexil/src/utils/CMakeFiles/PlexilUtils.dir/all' failed
> make[5]: *** [Modules/Plexil/src/utils/CMakeFiles/PlexilUtils.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make[4]: *** [all] Error 2
> CMakeFiles/cpu1-install.dir/build.make:57: recipe for target 'CMakeFiles/cpu1-install' failed
> make[3]: *** [CMakeFiles/cpu1-install] Error 2
> CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/cpu1-install.dir/all' failed
> make[2]: *** [CMakeFiles/cpu1-install.dir/all] Error 2
> CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/cpu1-install.dir/rule' failed
> make[1]: *** [CMakeFiles/cpu1-install.dir/rule] Error 2
> Makefile:175: recipe for target 'cpu1-install' failed
> make: *** [cpu1-install] Error 2

my ~/.bashrc file:

> root@username-VirtualBox:/home/username/icarous/icarous/build# cat ~/.bashrc
> # ~/.bashrc: executed by bash(1) for non-login shells.
> # see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
> # for examples
> 
> # If not running interactively, don't do anything
> [ -z "$PS1" ] && return
> 
> # don't put duplicate lines in the history. See bash(1) for more options
> # ... or force ignoredups and ignorespace
> HISTCONTROL=ignoredups:ignorespace
> 
> # append to the history file, don't overwrite it
> shopt -s histappend
> 
> # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
> HISTSIZE=1000
> HISTFILESIZE=2000
> 
> # check the window size after each command and, if necessary,
> # update the values of LINES and COLUMNS.
> shopt -s checkwinsize
> 
> # make less more friendly for non-text input files, see lesspipe(1)
> [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
> 
> # set variable identifying the chroot you work in (used in the prompt below)
> if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
>     debian_chroot=$(cat /etc/debian_chroot)
> fi
> 
> # set a fancy prompt (non-color, unless we know we "want" color)
> case "$TERM" in
>     xterm-color) color_prompt=yes;;
> esac
> 
> # uncomment for a colored prompt, if the terminal has the capability; turned
> # off by default to not distract the user: the focus in a terminal window
> # should be on the output of commands, not on the prompt
> #force_color_prompt=yes
> 
> if [ -n "$force_color_prompt" ]; then
>     if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
> 	# We have color support; assume it's compliant with Ecma-48
> 	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
> 	# a case would tend to support setf rather than setaf.)
> 	color_prompt=yes
>     else
> 	color_prompt=
>     fi
> fi
> 
> if [ "$color_prompt" = yes ]; then
>     PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
> else
>     PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
> fi
> unset color_prompt force_color_prompt
> 
> # If this is an xterm set the title to user@host:dir
> case "$TERM" in
> xterm*|rxvt*)
>     PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
>     ;;
> *)
>     ;;
> esac
> 
> # enable color support of ls and also add handy aliases
> if [ -x /usr/bin/dircolors ]; then
>     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
>     alias ls='ls --color=auto'
>     #alias dir='dir --color=auto'
>     #alias vdir='vdir --color=auto'
> 
>     alias grep='grep --color=auto'
>     alias fgrep='fgrep --color=auto'
>     alias egrep='egrep --color=auto'
> fi
> 
> # some more ls aliases
> alias ll='ls -alF'
> alias la='ls -A'
> alias l='ls -CF'
> 
> # Alias definitions.
> # You may want to put all your additions into a separate file like
> # ~/.bash_aliases, instead of adding them here directly.
> # See /usr/share/doc/bash-doc/examples in the bash-doc package.
> 
> if [ -f ~/.bash_aliases ]; then
>     . ~/.bash_aliases
> fi
> 
> # enable programmable completion features (you don't need to enable
> # this, if it's already enabled in /etc/bash.bashrc and /etc/profile
> # sources /etc/bash.bashrc).
> #if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
> #    . /etc/bash_completion
> #fi
> 
> PLEXIL_HOME="/home/username/icarous/icarous/Modules/Plextil"
> OSAL_HOME="/home/username/icarous/icarous/cFS/cFE/osal"
> JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"

**Comment by SweeWarman** [comment]
This seems to be an issue due to missing java related header files (jni.h). Can you check if you have the jni.h header file?  Ideally, this would be located somewhere under the folder you specify as JAVA_HOME. 

You could use the following command to locate the jni.h if it is already available:
sudo find / -name "jni.h"

**Comment by FabianSchuessler** [comment]
jni.h and the whole include folder was missing, I assume I only installed JRE instead of JDK. Now I got another error, zconf.h is missing. But /usr/include/zconf.h exists, so I think this might be another 32-bit vs 64bit issue that can be fixed by linking?

> root@username-VirtualBox:/home/username/icarous/icarous/build# make cpu1-install
> CMake Warning (dev) at cFS/cFE/cfe/cmake/version.cmake:52 (file):
>   Policy CMP0053 is not set: Simplify variable reference and escape sequence
>   evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   For input:
> 
>     '#define MISSION_CONFIG      \"@MISSIONCONFIG@\"\n'
> 
>   the old evaluation rules produce:
> 
>     '#define MISSION_CONFIG      "Icarous"
>     '
> 
>   but the new evaluation rules produce:
> 
>     '#define MISSION_CONFIG      "@MISSIONCONFIG@"
>     '
> 
>   Using the old result for compatibility since the policy is not set.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at cFS/cFE/cfe/cmake/version.cmake:52 (file):
>   Policy CMP0053 is not set: Simplify variable reference and escape sequence
>   evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   For input:
> 
>     '#define MISSION_NAME        \"@MISSION_NAME@\"\n'
> 
>   the old evaluation rules produce:
> 
>     '#define MISSION_NAME        "Icarous2"
>     '
> 
>   but the new evaluation rules produce:
> 
>     '#define MISSION_NAME        "@MISSION_NAME@"
>     '
> 
>   Using the old result for compatibility since the policy is not set.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> [  0%] Built target version
> [100%] Built target elf2cfetbl
> [100%] Built target mission-genfiles
> [ 32%] Built target ACCoRD
> [ 33%] Built target Utils
> [ 33%] Built target GeofenceMonitor
> [ 34%] Built target GeofenceTest
> [ 34%] Built target GeofenceTestC
> [ 43%] Built target ipc
> [ 43%] Built target pugixml
> [ 44%] Built target PlexilValue
> [ 48%] Built target PlexilUtils
> [ 52%] Built target PlexilExpr
> [ 55%] Built target PlexilIntfc
> [ 59%] Built target PlexilExec
> [ 63%] Built target PlexilXmlParser
> [ 67%] Built target PlexilAppFramework
> [ 68%] Built target PlexilSockets
> [ 69%] Built target UdpUtils
> [ 69%] Built target UdpAdapter
> [ 70%] Built target Launcher
> [ 71%] Built target GanttListener
> [ 71%] Built target IpcUtils
> [ 72%] Built target IpcAdapter
> [ 72%] Built target CfsAdapter
> [ 73%] Built target PlanDebugListener
> [ 73%] Built target LuvListener
> [ 73%] Built target universalExec
> [ 74%] Built target PlexilWrapper
> [ 74%] Building C object Modules/Plexil/src/wrapper/CMakeFiles/wrapperTest.dir/test.c.o
> /home/username/icarous/icarous/Modules/Plexil/src/wrapper/test.c:6:10: fatal error: zconf.h: No such file or directory
>  #include <zconf.h>
>           ^~~~~~~~~
> compilation terminated.
> Modules/Plexil/src/wrapper/CMakeFiles/wrapperTest.dir/build.make:62: recipe for target 'Modules/Plexil/src/wrapper/CMakeFiles/wrapperTest.dir/test.c.o' failed
> make[6]: *** [Modules/Plexil/src/wrapper/CMakeFiles/wrapperTest.dir/test.c.o] Error 1
> CMakeFiles/Makefile2:1769: recipe for target 'Modules/Plexil/src/wrapper/CMakeFiles/wrapperTest.dir/all' failed
> make[5]: *** [Modules/Plexil/src/wrapper/CMakeFiles/wrapperTest.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make[4]: *** [all] Error 2
> CMakeFiles/cpu1-install.dir/build.make:57: recipe for target 'CMakeFiles/cpu1-install' failed
> make[3]: *** [CMakeFiles/cpu1-install] Error 2
> CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/cpu1-install.dir/all' failed
> make[2]: *** [CMakeFiles/cpu1-install.dir/all] Error 2
> CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/cpu1-install.dir/rule' failed
> make[1]: *** [CMakeFiles/cpu1-install.dir/rule] Error 2
> Makefile:175: recipe for target 'cpu1-install' failed
> make: *** [cpu1-install] Error 2

> root@username-VirtualBox:/home/username/icarous/icarous/build# find / -name "zconf.h"
> /usr/include/zconf.h
> /usr/src/linux-headers-4.15.0-34/include/linux/zconf.h
> /usr/src/linux-headers-4.15.0-29/include/linux/zconf.h
> find: ‘/run/user/1000/gvfs’: Permission denied

**Comment by SweeWarman** [comment]
This is very strange. It seems like you have zconf.h. Your compiler should by default look into /usr/include and recognize zconf.h. 

Check if /usr/include is a default search path for your compiler. You can do this with the following command:

cpp -v

You should see something like:

#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include 
End of search list.

If /usr/include is not located on the search path, try setting the include path locations manually as follows:
export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/include

Hope this fixes the issue. If not, create a symbolic link to zconf.h in a location such as /usr/local/include or some other location where the compiler looks for .h files.

**Comment by FabianSchuessler** [comment]
Thank you very much for all your help. It is running now.
sudo apt-get install zlib1g-dev
solved the zconf.h problem
