### ISSUE TITLE
Question about interacting with ICAROUS

### ISSUE THREAD

**Issue by aogrcs** [nasa/icarous#54]
Hi
I want to interacting with ICAROUS, when I loaded the flightplan.txt and geofence.xml, I started it using long MISSION_START, I got result as the attachment, and I did not find any copter in the map? Is there any  wrong operation or did I miss something or I should use it with Arducopter? Thanks!
Sincerely

**Comment by SweeWarman** [comment]
I don't see any attachment. I'm not sure how you are using ICAROUS. Are you running ICAROUS with the arducopter software in the loop (SITL) simulator or are you connecting ICAROUS to the pixhawk? Regardless, to interact with ICAROUS, ICAROUS must first connect to either an autopilot (arducopter) or the SITL.  

ICAROUS is not a substitute for an autopilot. ICAROUS only provides planning and decision making functionality to make UAVs more autonomous. ICAROUS depends on an autopilot to perform the inner loop control (attitude control) and stabilization.

**Comment by FabianSchuessler** [comment]
If you have ICAROUS and arducopter installed on a drone, how do you connect both or verify the connection?

**Comment by aogrcs** [comment]
@SweeWarman sorry for the attachment, I would attach it tomorrow. I think I misunderstand the guide. Do you mean that ICAROUS should work with SITL or an hardware of ArduCopter? Thanks
@FabianSchuessler I do not have a drone having both ICAROUS and ArduCopter. Your work is very appreciated and if I got such a drone, I should do as you do. Hope for more detailed information. Thanks
Sincerely

**Comment by aogrcs** [comment]
@SweeWarman This is the attachment. I thought that I could only use runGS.sh or runSITL.sh to simulate both ICAROUS and ArduCopter! This is completely wrong! Thanks













![default](https://user-images.githubusercontent.com/5660925/46850527-dd333580-ce26-11e8-95f5-c8ec2e899191.JPG)

**Comment by SweeWarman** [comment]
@FabianSchuessler If ICAROUS is connect to a drone, and assuming your ground station has a radio connection to the companion computer on which ICAROUS is running and all the port settings in the ardupilot app have been configured appropriately, you should be able to receive telemetry on your ground station. This is an indication that ICAROUS is working. ICAROUS reroute telemetry packets from the pixhawk to the ground station via the companion computer:

Pixhawk <-> (telem 1/2 serial port) <-> ICAROUS (on companion computer) <-> radio connected to companion computer <-> ground station. 

Also, if you have a terminal connected to the companion computer, when you launch ICAROUS, you should see a status message saying "Connection to autopilot established" on the terminal where you launch icarous with core-cpu1.

**Comment by aogrcs** [comment]
@SweeWarman Thanks for your explanation.
