### ISSUE TITLE
problems with ./runGS.sh

### ISSUE THREAD

**Issue by marselomeri** [nasa/icarous#58]
I am having problems while running ./runGS.sh.  The error is shown in the screen-shot below. Could you give me any hint, how to fix it ?

![Screenshot from 2019-07-12 17-28-30](https://user-images.githubusercontent.com/41054948/61140975-ce200780-a4cc-11e9-84ea-ef7f29b25cce.png)

**Comment by SweeWarman** [comment]
Are you able to run mavproxy.py from the command line?
