### ISSUE TITLE
How to use geofence.

### ISSUE THREAD

**Issue by Fauconer** [nasa/icarous#60]
Hi,
I run Icarous ( `sudo ./core-cpu1 -I 0 -C 1`)
Then I run the SITL : 
`cd ~/Documents/BE/Git/ardupilot/Tools/autotest
sudo ./sim_vehicle.py  -l 37.101783,-76.382997,0,270 -v APMrover2 --map --console`

icarous displays : 
EVS Port1 0/1/ARDUPILOT 3: Connection to autopilot established
EVS Port1 0/1/SCH 18: Multiple slots processed: slot = 0, count = 2

Then we load the geofence module and then the geofence.xml file but I'm not on how to test the keep in and keep out violations.
Could you provide us with some information about how to use the geofence and traffic modules ?

Thank you.

**Comment by SweeWarman** [comment]
1. The current version of Icarous only supports ArduCopter. I see that you are running SITL with AMProver2. It's best to use `-v ArduCopter`.

2. To upload geofences, you'll have to install the custom mavproxy modules found under [here](https://github.com/nasa/icarous/tree/master/Python/CustomModules). See the "INTERACTING WITH ICAROUS" section in the README.

3. Start mavproxy with the custom modules. You can use this script [here](https://github.com/nasa/icarous/blob/master/Scripts/runGS.sh). If you installed the custom modules as described above, you should be able to use the geofence command on the mavproxy terminal.

4. We provide sample flight plans and geofences if you'd like to observe Icarous' response against potential keep in and keep out violations. Upload Examples/InputData/flightplan.txt as a flightplan and upload Examples/InputData/geofence2.xml as the geofence. 

Please note that although sim_vehicle.py opens its own mavproxy terminal, you should be running a separate mavproxy instance to communicate with Icarous. The dataflow is as follows:

SITL with Mavproxy <----> Icarous-cFS <-----> Mavproxy
 ( sim_vehicle.py)                  (core-cpu1)

Hope this helps.

**Comment by Fauconer** [comment]
Hi, 

thank you for your advice, I followed your instructions but Icarous doesn't seem respond when the vehicle enters the red zone created with geofence2.xml, as shown in the attachment. 
![Icarous problem](https://user-images.githubusercontent.com/56804233/71969659-680c0700-3207-11ea-9a96-ebad3524a7f8.png)

Moreover I simulated an intruder with the traffic module and the same problem occurred. 

Many thanks.

**Comment by marselomeri** [comment]
Hi, 
I believe that you should run all the commands through the mavproxy terminal. In the picture it looks like you are running the command 'long mission_start' from the terminal where you are running the autopilot (ArduCopter in this case). 
So in the terminal where you run ./runGS: 
1. load the flightplan
2. load the geofence
3. long MISSION_START

**Comment by SweeWarman** [comment]
@Fauconer As I mentioned in my previous comment, there are two mavproxy instances in this setup. One is opened by SITL. This mavproxy instance is not connected to Icarous. Any commands you type here is only sent to SITL and not Icarous. You shouldn't be doing anything on this mavproxy terminal unless you want to directly interact with the SITL. If you want to interact with ICAROUS, you need to use the second mavproxy instance. In the image you sent me, you are sending the long MISSION_START command in the wrong mavproxy instance.

**Comment by Fauconer** [comment]
Hi, 
Thank you for your help. 
The geofence module operates correctly now.
