### ISSUE TITLE
GPS-Denied???

### ISSUE THREAD

**Issue by plushpluto** [nasa/icarous#64]
Any way to disable the GPS?

**Comment by SweeWarman** [comment]
I am not sure I understand what you are trying to do. A little more context would be helpful.

In general, Icarous internally uses GPS coordinates. If you don't have GPS data but have some notion of local position (based on SLAM, VICON or other external positioning systems), I would recommend converting from local coordinates to GPS coordinates before feeding in data to Icarous. Currently, we only provide an interface application to the arducopter autopilot. This application is not setup to receive local coordinates. But you can develop your own interface applications or modify the arducopter interface to receive local position values and convert them into a GPS coordinates before publishing them to Icarous.

**Comment by plushpluto** [comment]
Hey sorry! I am a regular user of ardupilot/px4 systems and trying to simulate random GPS-denied environments during flight. I understand that Icarous is heavily dependent on GPS coordinates. 

"This application is not setup to receive local coordinates." is a bummer. It's ok. I shall try and reverse-engineer the Geofence layer. On the top of my head, when you can geofence with an UAV inside, should be able to geofence that doesn't allow one. Don't know. I may be wrong!! 

But hey, I am a fan of your work man. Really nice effort in bringing up Icarous/Diadalus. The communication layer seems to be the key and is nicely built.
