### ISSUE TITLE
ICAROUS build issues

### ISSUE THREAD

**Issue by tamtran1** [nasa/icarous#66]
Hi, I'm trying to build icarous. I cloned the repository and followed the user guide from the link in the readme to build the project but I get an error at PC_Quadcopter_Simulation.h, it says no such file or directory. it look like this file belongs in a submodule app/rotorsim. but when trying to call `git submodule update --init --recursive` I get permission issue fetching from the remote repository, it says fatal: Could not read from remote repository. I did use `UpdateModules.sh` to fetch the public modules as instructed by the user guide, but apparently the build also requires content from the non-public ones as well.
So how do I overcome this issue to continue with my build?
Thanks

**Comment by SweeWarman** [comment]
@tamtran1  You shouldn't be using the git submodule update command directly. I recommend you do the following:
- Create a fresh clone of the icarous repository
- Update the submodules using UpdateModules.sh
- In [apps.cmake](https://github.com/nasa/icarous/blob/master/Icarous_defs/apps.cmake#L5) change "rotorsim" to "arducopter":
- Continue with the build with
    - make
    - make install

**Comment by SweeWarman** [comment]
@tamtran1 since there are no further responses from you, we'll be closing this issue. If you have further questions, please reopen this issue.
