### ISSUE TITLE
execution issue

### ISSUE THREAD

**Issue by marselomeri** [nasa/icarous#68]
Hi, 
I am having an error when I execute the file "./core-cpu1".  I don't get any errors during the build and compilation of the code. It seems that there is some problem with OS_Posix and I am testing it on Ubuntu 20.04. 
Any hint what might be wrong, would be helpful ! 
Attached is a screen shot, who can show the error. 
![icarous_exe](https://user-images.githubusercontent.com/41054948/88706372-137f9900-d111-11ea-821f-f7ebad1ed533.png)

**Comment by SweeWarman** [comment]
Could you try without sudo and see if it works?

**Comment by marselomeri** [comment]
Yes, it seems to work without sudo. Thanks!
