### ISSUE TITLE
issues about running core-cpu1

### ISSUE THREAD

**Issue by vvrn1** [nasa/icarous#69]
Hi, I have run into an issue after building the ICAROUS.
I cannot find the App Startup file: /cf/cfe_es_startup.scr after "make" and "make install".
![2020-10-04 08-49-04 的屏幕截图](https://user-images.githubusercontent.com/9376886/95004525-c6dba100-061e-11eb-9c4f-9b6bfcb6ee4f.png)
Is there anything wrong?

**Comment by SweeWarman** [comment]
Did you get any errors/warnings when you ran make? Delete the build folder under icarous/ and run make again while saving the output to a file: e.g.: make > mkout.txt 2>&1 

Attach the mkout.txt file here so that I can take a look at the output.

**Comment by vvrn1** [comment]
> Did you get any errors/warnings when you ran make? Delete the build folder under icarous/ and run make again while saving the output to a file: e.g.: make > mkout.txt 2>&1
> 
> Attach the mkout.txt file here so that I can take a look at the output.

Thanks for replying. Here is the mkout.txt
[mkout.txt](https://github.com/nasa/icarous/files/5332292/mkout.txt)

**Comment by vvrn1** [comment]
Sorry, I found it works after rebuilding!
Another question is that I wanna connect ICAROUS (TCL4+, e.g) with Ardupilot SITL but I have little experience before. Could you offer me some tips ?

**Comment by SweeWarman** [comment]
Instructions on running SITL can be found here:  https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html. Currently Icarous only supports the "ArduCopter". So make sure you use the "-v ArduCopter" flag. Icarous should automatically connect to the SITL if you have Icarous running.

Look at these instructions as well to interact with Icarous: https://nasa.github.io/icarous/interacting.html

**Comment by vvrn1** [comment]
> Instructions on running SITL can be found here: https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html. Currently Icarous only supports the "ArduCopter". So make sure you use the "-v ArduCopter" flag. Icarous should automatically connect to the SITL if you have Icarous running.
> 
> Look at these instructions as well to interact with Icarous: https://nasa.github.io/icarous/interacting.html

Thanks for your reply. I have run ./icarous/Python/TestRunner/RunScenarios.py. It seems working but I cannot see geofence in the map and the parameter "--plot" seems not working.
![Uploading 2020-10-06 22-42-31 的屏幕截图.png…]()

**Comment by vvrn1** [comment]
> Instructions on running SITL can be found here: https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html. Currently Icarous only supports the "ArduCopter". So make sure you use the "-v ArduCopter" flag. Icarous should automatically connect to the SITL if you have Icarous running.
> 
> Look at these instructions as well to interact with Icarous: https://nasa.github.io/icarous/interacting.html

Thanks for your reply. I have run ./icarous/Python/TestRunner/RunScenarios.py. It seems working but I cannot see geofence in the map and the parameter "--plot" seems not working.
![2020-10-06 22-42-31 的屏幕截图](https://user-images.githubusercontent.com/9376886/95217803-31126280-0826-11eb-9d83-793a8fce0bf0.png)

**Comment by SweeWarman** [comment]
The RunScenarios.py is meant to run scenarios without a user interface in a scripted manner. Using this script will not provide you any visual feedback for the geofences or flightplans. The --plot argument must be used with the --validate argument. This will create several matplotlib plots of mission profiles, aircraft states etc.. after the simulation is complete. 

To see geofences, you must have a ground station connected as explained [here](https://nasa.github.io/icarous/interacting.html). If you are decide to use mavproxy (v1.8.9 and above is not supported), you must have installed the custom modules as instructed.

**Comment by vvrn1** [comment]
> The RunScenarios.py is meant to run scenarios without a user interface in a scripted manner. Using this script will not provide you any visual feedback for the geofences or flightplans. The --plot argument must be used with the --validate argument. This will create several matplotlib plots of mission profiles, aircraft states etc.. after the simulation is complete.
> 
> To see geofences, you must have a ground station connected as explained [here](https://nasa.github.io/icarous/interacting.html). If you are decide to use mavproxy (v1.8.9 and above is not supported), you must have installed the custom modules as instructed.

Thanks for your reply. I'll try it soon.

**Comment by vvrn1** [comment]
> The RunScenarios.py is meant to run scenarios without a user interface in a scripted manner. Using this script will not provide you any visual feedback for the geofences or flightplans. The --plot argument must be used with the --validate argument. This will create several matplotlib plots of mission profiles, aircraft states etc.. after the simulation is complete.
> 
> To see geofences, you must have a ground station connected as explained [here](https://nasa.github.io/icarous/interacting.html). If you are decide to use mavproxy (v1.8.9 and above is not supported), you must have installed the custom modules as instructed.

Sorry to bother you again. I have installed the custom modules as instructed and ran ./runSITL.sh. Also, I opened another terminal and ran an individual sim_vehicle.py in Arducopter. However it seems not work and some errors occur in the terminal window.
![2020-10-08 15-44-55 的屏幕截图](https://user-images.githubusercontent.com/9376886/95429658-464dd500-097d-11eb-8163-38c9afa3e4c9.png)

**Comment by SweeWarman** [comment]
Sorry for the late response. These errors seem like they are related to MAVProxy/SITL and not Icarous.
