### ISSUE TITLE
Build error - multiple definitions of appdata.Intgs

### ISSUE THREAD

**Issue by MarinLGU** [nasa/icarous#71]
Hi,
I'm trying to build ICAROUS in order to test it along with the WebGS, but when building ICAROUS it stops at  `[ 61%] Linking C shared module gsInterface.so
/usr/bin/ld: CMakeFiles/gsInterface.dir/fsw/src/gsProcessMessages.c.o:/PathToIcarous/icarous/apps/gsInterface/fsw/src/gsInterface.h:194: multiple definition of appdataIntGS; CMakeFiles/gsInterface.dir/fsw/src/gsInterface.c.o:/PathToIcarous/icarous/apps/gsInterface/fsw/src/gsInterface.h:194: first defined here`
Do you have any idea where it could come from ?
Thanks,
Marin

**Comment by SweeWarman** [comment]
Unless you've made any changes to the source files (have you?), this error message doesn't make much sense to me. There is only one definition for appdataIntGS. I am not able to reproduce this issue on my end with the version on master. It seems to be compiling and linking fine. Are you following the compilation instructions here: https://nasa.github.io/icarous/compiling.html? I would suggest removing the build folder and trying again.

**Comment by MarinLGU** [comment]
Thanks for your reply,
I didn't make any change to the source code, and I'm compiling the version cloned from master... I agree with you analysis I could only find one definition but I'm not a C/C++ expert by far. I am running Fedora 33, GNU Make 4.3, gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9). After deleting the Build folder I have the same issue, I will continue to look on my side. Thanks

**Comment by SweeWarman** [comment]
I've never tried compiling on Fedora. We've only used Debian-based distros so far. Let me run a few tests and get back to you.

**Comment by SweeWarman** [comment]
Ok.. so I think I understand what is happening. Will push a fix and let you know.

**Comment by MarinLGU** [comment]
Thanks a lot ! I'll try compiling as soon as the push is done and let you know if the fix works :)

**Comment by SweeWarman** [comment]
Please pull and try again.

**Comment by MarinLGU** [comment]
It compiles now ! Thanks a lot. If I understand well the simulation with Rotorsim is no longer available but it can be done with Ardupilot in SITL mode ?

**Comment by SweeWarman** [comment]
Yes. That is correct!
