### ISSUE TITLE
traffic data not recorded in json file

### ISSUE THREAD

**Issue by marselomeri** [nasa/icarous#78]
Hello, 
when I try to run python3 RunPySim.py  and use --cfs as argument, the traffic data is not recorded. The traffic is added because the ownship does a maneuver during the simulation but no information is stored. 

Could you give me any idea how to fix this? 

Thanks

**Comment by SweeWarman** [comment]
I made a few tests and it seems like the traffic is being recorded in the json logs. Could you attach your json log file here so that I can take a look at it?

**Comment by marselomeri** [comment]
Here you may find attached a json log. 
[simlog-SPEEDBIRD.zip](https://github.com/nasa/icarous/files/6405744/simlog-SPEEDBIRD.zip)

I also use ArduCopter as autopilot for my tests.

**Comment by marselomeri** [comment]
It seems to be working after your latest update, thank you !

**Comment by marselomeri** [comment]
Hello, 
the latest update fixed the traffic record, but there is still is an issue related to the number of logs. As you can see in screenshot attached, Ownship logs are [1193] , whereas Traffic logs are [1410].  Any hint of what might be causing this?

I am using Ubuntu 20.04, and ArduCopter. 
Thanks
![Screenshot from 2021-05-03 20-54-55](https://user-images.githubusercontent.com/41054948/116920747-513ac080-ac53-11eb-9b93-8784e90154b9.png)

**Comment by SweeWarman** [comment]
This is not an issue. This simply means the traffic states are being recorded more often than the ownship states. If you are looking for the corresponding position of the intruder for a given ownship position, you should focus on the time associated with each entry (not the index).
